=== tomwadley/old-ship/src/shipmod.dtd
<!ELEMENT shipmod (description,picMaskColour,newGame,healthPrice,enemies,ships,weapons,backgroundobjects,levels)>
	<!ATTLIST shipmod name CDATA #REQUIRED>
	<!ATTLIST shipmod shipmodversion CDATA #REQUIRED>

	<!ELEMENT newGame (weaponsOwnedNames,shipsOwnedNames)>
		<!ELEMENT weaponsOwnedNames (weaponName*)>
		<!ELEMENT shipsOwnedNames (shipName*)>
	
	<!ELEMENT healthPrice (qty,cost)>

	<!ELEMENT enemies (enemy*)>
		<!ELEMENT enemy (obName,minMoveTop,maxMoveTop,minMoveLeft,maxMoveLeft,maxHealth,weaponName,pics,timeBetweenPics,picsDead,timeBetweenPicsDead,cash,initReloadTime,entryPoint,entrySide,entrySideChange)>
	<!ELEMENT ships (ship*)>
		<!ELEMENT ship (obName,moveSpeed,maxHealth,reloadTimeMultiplier,collisionWeaponName,collisionProjectileFromWeaponName,pics,timeBetweenPics,picsDead,timeBetweenPicsDead,cost,description,title)>
	<!ELEMENT weapons (weapon*)>
		<!ELEMENT weapon (obName,projectiles,cost,description,title)>
			<!ELEMENT projectiles (projectile*)>
				<!ELEMENT projectile (obName,column,row,customColumn,customRow,moveTop,moveLeft,tracksPlayer,pics,timeBetweenPics,picsDead,timeBetweenPicsDead,damage,reloadTime,initReloadTime)>
	<!ELEMENT backgroundobjects (backgroundobject*)>
		<!ELEMENT backgroundobject (obName,moveSpeed,pics,timeBetweenPics,chanceOfCreation)>
	<!ELEMENT levels (level*)>
		<!ELEMENT level (obName,title,description,dependenciesNames,enemiesPresent,levelTime,backgroundobjectsPresentNames,bossName,backgroundColour,backImageBackgroundobjectName,enemiesStartTime,bossFinalX,bossFinalY)>
			<!ELEMENT dependenciesNames (dependencieName*)>
			<!ELEMENT enemiesPresent (enemyPresent*)>
				<!ELEMENT enemyPresent (enemyName,chanceOfCreation,maxOnScreen)>
			<!ELEMENT backgroundobjectsPresentNames (backgroundobjectPresentName*)>
				


<!ELEMENT pics (pic*)>
<!ELEMENT picsDead (pic*)>
	<!ELEMENT pic (#PCDATA)>

<!ELEMENT obName (#PCDATA)>
<!ELEMENT minMoveTop (#PCDATA)>
<!ELEMENT maxMoveTop (#PCDATA)>
<!ELEMENT minMoveLeft (#PCDATA)>
<!ELEMENT maxMoveLeft (#PCDATA)>
<!ELEMENT maxHealth (#PCDATA)>
<!ELEMENT weaponName (#PCDATA)>
<!ELEMENT shipName (#PCDATA)>
<!ELEMENT moveSpeed (#PCDATA)>
<!ELEMENT reloadTimeMultiplier (#PCDATA)>
<!ELEMENT collisionWeaponName (#PCDATA)>
<!ELEMENT collisionProjectileFromWeaponName (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT column (#PCDATA)>
<!ELEMENT row (#PCDATA)>
<!ELEMENT moveTop (#PCDATA)>
<!ELEMENT moveLeft (#PCDATA)>
<!ELEMENT tracksPlayer (#PCDATA)>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT reloadTime (#PCDATA)>
<!ELEMENT initReloadTime (#PCDATA)>
<!ELEMENT chanceOfCreation (#PCDATA)>
<!ELEMENT levelTime (#PCDATA)>
<!ELEMENT bossName (#PCDATA)>
<!ELEMENT backgroundColour (#PCDATA)>
<!ELEMENT backImageBackgroundobjectName (#PCDATA)>
<!ELEMENT enemiesStartTime (#PCDATA)>
<!ELEMENT bossFinalX (#PCDATA)>
<!ELEMENT bossFinalY (#PCDATA)>
<!ELEMENT dependencieName (#PCDATA)>
<!ELEMENT backgroundobjectPresentName (#PCDATA)>
<!ELEMENT timeBetweenPics (#PCDATA)>
<!ELEMENT timeBetweenPicsDead (#PCDATA)>
<!ELEMENT cash (#PCDATA)>
<!ELEMENT entryPoint (#PCDATA)>
<!ELEMENT entrySide (#PCDATA)>
<!ELEMENT entrySideChange (#PCDATA)>
<!ELEMENT enemyName (#PCDATA)>
<!ELEMENT maxOnScreen (#PCDATA)>
<!ELEMENT picMaskColour (#PCDATA)>
<!ELEMENT customColumn (#PCDATA)>
<!ELEMENT customRow (#PCDATA)>
<!ELEMENT qty (#PCDATA)>

=== tomwadley/old-ship/demo-mod/demo.xml
<?xml version="1.0"?>
<!DOCTYPE shipmod SYSTEM "shipmod.dtd">

<shipmod name="demo" shipmodversion="1">
	<description>This is a demonstration ship mod. This mod is very short and crappy. Ship 1.0 will come standard with a far better mod. For now, this will have to do (Or you could make your own mod. Its pretty simple. Just open demo.xml and try changing the values)  --Mod By Tom Wadley with pics from Liam Fitzpatrick and Harley Wilmott--</description>
	<picMaskColour>0</picMaskColour>
	<newGame>
		<weaponsOwnedNames>
			<weaponName>plasma player</weaponName>
		</weaponsOwnedNames>
		<shipsOwnedNames>
			<shipName>blue player</shipName>
		</shipsOwnedNames>
	</newGame>
	<healthPrice>
		<qty>20</qty>
		<cost>400</cost>
	</healthPrice>

	<!--These are the values for entryPoint and enetrySide for enemies
		entryPoint:
		epTop = 0
		epBottom = 1
		epLeft = 2
		epRight = 3

		entrySide:
		epLeftSide = 0
		epRightSide = 1
		epMiddleSide = 2
		epAnywhereSide = 3
	-->
	<enemies>
		<enemy>
			<obName>grey enemy</obName>
			<minMoveTop>1500</minMoveTop>
			<maxMoveTop>2000</maxMoveTop>
			<minMoveLeft>0</minMoveLeft>
			<maxMoveLeft>0</maxMoveLeft>
			<maxHealth>10</maxHealth>
			<weaponName>missile enemy</weaponName>
			<pics>
				<pic>grey enemy-1.bmp</pic>
				<pic>grey enemy-2.bmp</pic>
			</pics>
			<timeBetweenPics>0.1</timeBetweenPics>
			<picsDead>
				<pic>explosion-1.bmp</pic>
				<pic>explosion-2.bmp</pic>
			</picsDead>
			<timeBetweenPicsDead>0.3</timeBetweenPicsDead>
			<cash>100</cash>
			<initReloadTime>1</initReloadTime>
			<entryPoint>0</entryPoint>
			<entrySide>3</entrySide>
			<entrySideChange>0</entrySideChange>
		</enemy>
		<enemy>
			<obName>rust enemy</obName>
			<minMoveTop>2000</minMoveTop>
			<maxMoveTop>2500</maxMoveTop>
			<minMoveLeft>0</minMoveLeft>
			<maxMoveLeft>0</maxMoveLeft>
			<maxHealth>8</maxHealth>
			<weaponName>dual fireball enemy</weaponName>
			<pics>
				<pic>rust enemy-1.bmp</pic>
				<pic>rust enemy-2.bmp</pic>
				<pic>rust enemy-3.bmp</pic>
				<pic>rust enemy-4.bmp</pic>
				<pic>rust enemy-5.bmp</pic>
				<pic>rust enemy-6.bmp</pic>
			</pics>
			<timeBetweenPics>0.1</timeBetweenPics>
			<picsDead>
				<pic>explosion-1.bmp</pic>
				<pic>explosion-2.bmp</pic>
			</picsDead>
			<timeBetweenPicsDead>0.3</timeBetweenPicsDead>
			<cash>150</cash>
			<initReloadTime>1</initReloadTime>
			<entryPoint>0</entryPoint>
			<entrySide>3</entrySide>
			<entrySideChange>0</entrySideChange>
		</enemy>
		<enemy>
			<obName>green enemy</obName>
			<minMoveTop>1150</minMoveTop>
			<maxMoveTop>1350</maxMoveTop>
			<minMoveLeft>0</minMoveLeft>
			<maxMoveLeft>0</maxMoveLeft>
			<maxHealth>28</maxHealth>
			<weaponName>gunk enemy</weaponName>
			<pics>
				<pic>green ship-1.bmp</pic>
				<pic>green ship-2.bmp</pic>
				<pic>green ship-3.bmp</pic>
			</pics>
			<timeBetweenPics>0.1</timeBetweenPics>
			<picsDead>
				<pic>green ship dead-1.bmp</pic>
				<pic>green ship dead-2.bmp</pic>
				<pic>green ship dead-3.bmp</pic>
				<pic>green ship dead-4.bmp</pic>
				<pic>green ship dead-5.bmp</pic>
				<pic>green ship dead-6.bmp</pic>
			</picsDead>
			<timeBetweenPicsDead>0.1</timeBetweenPicsDead>
			<cash>300</cash>
			<initReloadTime>1</initReloadTime>
			<entryPoint>0</entryPoint>
			<entrySide>3</entrySide>
			<entrySideChange>0</entrySideChange>
		</enemy>
		<enemy>
			<obName>boss enemy</obName>
			<minMoveTop>300</minMoveTop>
			<maxMoveTop>300</maxMoveTop>
			<minMoveLeft>0</minMoveLeft>
			<maxMoveLeft>0</maxMoveLeft>
			<maxHealth>300</maxHealth>
			<weaponName>boss enemy</weaponName>
			<pics>
				<pic>boss enemy-1.bmp</pic>
				<pic>boss enemy-2.bmp</pic>
				<pic>boss enemy-3.bmp</pic>
				<pic>boss enemy-4.bmp</pic>
				<pic>boss enemy-5.bmp</pic>
				<pic>boss enemy-6.bmp</pic>
				<pic>boss enemy-7.bmp</pic>
				<pic>boss enemy-8.bmp</pic>
				<pic>boss enemy-9.bmp</pic>
				<pic>boss enemy-10.bmp</pic>
				<pic>boss enemy-11.bmp</pic>
				<pic>boss enemy-12.bmp</pic>
			</pics>
			<timeBetweenPics>0.1</timeBetweenPics>
			<picsDead>
				<pic>boss dead enemy-1.bmp</pic>
				<pic>boss dead enemy-2.bmp</pic>
				<pic>boss dead enemy-3.bmp</pic>
				<pic>boss dead enemy-4.bmp</pic>
			</picsDead>
			<timeBetweenPicsDead>0.3</timeBetweenPicsDead>
			<cash>1000</cash>
			<initReloadTime>5</initReloadTime>
			<entryPoint>0</entryPoint>
			<entrySide>2</entrySide>
			<entrySideChange>0</entrySideChange>
		</enemy>
		<enemy>
			<obName>asteroid L-R</obName>
			<minMoveTop>1000</minMoveTop>
			<maxMoveTop>1000</maxMoveTop>
			<minMoveLeft>800</minMoveLeft>
			<maxMoveLeft>1200</maxMoveLeft>
			<maxHealth>1</maxHealth>
			<weaponName></weaponName>
			<pics>
				<pic>asteroid-1.bmp</pic>
				<pic>asteroid-2.bmp</pic>
				<pic>asteroid-3.bmp</pic>
				<pic>asteroid-4.bmp</pic>
			</pics>
			<timeBetweenPics>0.25</timeBetweenPics>
			<picsDead>
				<pic>asteroiddead-1.bmp</pic>
				<pic>asteroiddead-2.bmp</pic>
				<pic>asteroiddead-3.bmp</pic>
				<pic>asteroiddead-4.bmp</pic>
			</picsDead>
			<timeBetweenPicsDead>0.2</timeBetweenPicsDead>
			<cash>0</cash>
			<initReloadTime>1</initReloadTime>
			<entryPoint>2</entryPoint>
			<entrySide>3</entrySide>
			<entrySideChange>4000</entrySideChange>
		</enemy>
		<enemy>
			<obName>asteroid T-R</obName>
			<minMoveTop>1000</minMoveTop>
			<maxMoveTop>1000</maxMoveTop>
			<minMoveLeft>800</minMoveLeft>
			<maxMoveLeft>1200</maxMoveLeft>
			<maxHealth>1</maxHealth>
			<weaponName></weaponName>
			<pics>
				<pic>asteroid-1.bmp</pic>
				<pic>asteroid-2.bmp</pic>
				<pic>asteroid-3.bmp</pic>
				<pic>asteroid-4.bmp</pic>
			</pics>
			<timeBetweenPics>0.25</timeBetweenPics>
			<picsDead>
				<pic>asteroiddead-1.bmp</pic>
				<pic>asteroiddead-2.bmp</pic>
				<pic>asteroiddead-3.bmp</pic>
				<pic>asteroiddead-4.bmp</pic>
			</picsDead>
			<timeBetweenPicsDead>0.2</timeBetweenPicsDead>
			<cash>0</cash>
			<initReloadTime>1</initReloadTime>
			<entryPoint>0</entryPoint>
			<entrySide>3</entrySide>
			<entrySideChange>2000</entrySideChange>
		</enemy>
	</enemies>

	<ships>
		<ship>
			<obName>blue player</obName>
			<moveSpeed>5000</moveSpeed>
			<maxHealth>100</maxHealth>
			<reloadTimeMultiplier>1</reloadTimeMultiplier>
			<collisionWeaponName>collission</collisionWeaponName>
			<collisionProjectileFromWeaponName>main</collisionProjectileFromWeaponName>
			<pics>
				<pic>blue player-1.bmp</pic>
				<pic>blue player-2.bmp</pic>
			</pics>
			<timeBetweenPics>0.1</timeBetweenPics>
			<picsDead>
				<pic>explosion-1.bmp</pic>
				<pic>explosion-2.bmp</pic>
			</picsDead>
			<timeBetweenPicsDead>0.3</timeBetweenPicsDead>
			<cost>0</cost>
			<description>The classic starter ship.</description>
			<title>Classic Ship</title>
		</ship>
		<ship>
			<obName>tank player</obName>
			<moveSpeed>4500</moveSpeed>
			<maxHealth>200</maxHealth>
			<reloadTimeMultiplier>0.8</reloadTimeMultiplier>
			<collisionWeaponName>collission</collisionWeaponName>
			<collisionProjectileFromWeaponName>main</collisionProjectileFromWeaponName>
			<pics>
				<pic>hulk player-1.bmp</pic>
				<pic>hulk player-2.bmp</pic>
				<pic>hulk player-3.bmp</pic>
				<pic>hulk player-4.bmp</pic>
			</pics>
			<timeBetweenPics>0.175</timeBetweenPics>
			<picsDead>
				<pic>hulk dead player-1.bmp</pic>
				<pic>hulk dead player-2.bmp</pic>
			</picsDead>
			<timeBetweenPicsDead>0.2</timeBetweenPicsDead>
			<cost>3000</cost>
			<description>This ship moves slightly slower but fires slightly faster and has 200 health.</description>
			<title>Tank ship</title>
		</ship>
	</ships>

	<!--These are the values for column and row in projectiles 
		column:
		wpFarLeft = 1
		wpLeft = 2
		wpRight = 3
		wpFarRight = 4
		
		row:
		wpFarFront = 1
		wpFront = 2
		wpBack = 3
		wpFarBack = 4

		both:
		wpCustom = 0
	-->
	<weapons>
		<weapon>
			<obName>missile enemy</obName>
			<projectiles>
				<projectile>
					<obName>1</obName>
					<column>0</column>
					<row>4</row>
					<customColumn>0.5</customColumn>
					<customRow>0</customRow>
					<moveTop>4000</moveTop>
					<moveLeft>0</moveLeft>
					<tracksPlayer>FALSE</tracksPlayer>
					<pics>
						<pic>missile enemy-1.bmp</pic>
						<pic>missile enemy-2.bmp</pic>
					</pics>
					<timeBetweenPics>0.1</timeBetweenPics>
					<picsDead>
						<pic>missile dead-1.bmp</pic>
						<pic>missile dead-2.bmp</pic>
					</picsDead>
					<timeBetweenPicsDead>0.2</timeBetweenPicsDead>
					<damage>10</damage>
					<reloadTime>1.5</reloadTime>
					<initReloadTime>0</initReloadTime>
				</projectile>
			</projectiles>
			<cost>-1</cost>
			<description></description>
			<title></title>
		</weapon>
		<weapon>
			<obName>dual fireball enemy</obName>
			<projectiles>
				<projectile>
					<obName>left</obName>
					<column>2</column>
					<row>4</row>
					<customColumn>0</customColumn>
					<customRow>0</customRow>
					<moveTop>4000</moveTop>
					<moveLeft>-3000</moveLeft>
					<tracksPlayer>FALSE</tracksPlayer>
					<pics>
						<pic>fireball-1.bmp</pic>
						<pic>fireball-2.bmp</pic>
					</pics>
					<timeBetweenPics>0.1</timeBetweenPics>
					<picsDead>
						<pic>fireball dead-1.bmp</pic>
						<pic>fireball dead-2.bmp</pic>
					</picsDead>
					<timeBetweenPicsDead>0.1</timeBetweenPicsDead>
					<damage>5</damage>
					<reloadTime>0.75</reloadTime>
					<initReloadTime>0</initReloadTime>
				</projectile>
				<projectile>
					<obName>right</obName>
					<column>3</column>
					<row>4</row>
					<customColumn>0</customColumn>
					<customRow>0</customRow>
					<moveTop>4000</moveTop>
					<moveLeft>3000</moveLeft>
					<tracksPlayer>FALSE</tracksPlayer>
					<pics>
						<pic>fireball-1.bmp</pic>
